### PR TITLE
Rebuild

### PR DESCRIPTION
**Pull request by codeclubrobot**
Hello!

I've been hard at work, rebuilding the Code Club UK projects website from the latest markdown.

I ran my scheduled nightly build and I found some updates, so I thought I'd best send a pull request. You can view my updated version here:
http://codeclubrobot.github.io/CodeClubUK-Projects/

Have a nice day!

### CODE REVIEW

**Comment by CodeClubRik** [comment]
hey @andylolz do you have any idea why this isn't building? it mentions a missing image in the vietnamese translation of the 'fireworks' project?

**Comment by andylolz** [comment]
Standard thing – phantom.js crashed while it was generating a scratchblock image (in the Vietnamese fireworks project.)

Possible fixes:
 * spot the crashes and re-run. We should be doing this anyway, but as I recall there was some problem with error codes (I will look into this).
 * prevent crashes by figuring out what is causing them to happen all the time. I think I looked into this and decided it was to do with phantom.js eating up resources or having memory leaks or something.

**Comment by CodeClubRik** [comment]
Oh, I see! I thought it might be a problem with the manifest or something. I'm happy to just spot and re-run for now if it's an occasional thing (which it appears to be).

**Comment by andylolz** [comment]
You can actually see the problem on the @codeclubrobot build. It’s right near the end of this page:
http://codeclubrobot.github.io/CodeClubUK-Projects/vi-VN/01_scratch/03/Fireworks.html

**Pull request merged**
